/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as IndexRouteImport } from './app/router/index'
import { Route as AuthRouteRouteImport } from './app/router/_auth/route'
import { Route as AuthGetStartedRouteImport } from './app/router/_auth/get-started'
import { Route as AuthSetUsernameRouteImport } from './app/router/_auth/set-username'
import { Route as AuthVerifyRouteImport } from './app/router/_auth/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGetStartedRoute = AuthGetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetUsernameRoute = AuthSetUsernameRouteImport.update({
  id: '/set-username',
  path: '/set-username',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof AuthGetStartedRoute
  '/set-username': typeof AuthSetUsernameRoute
  '/verify': typeof AuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof AuthGetStartedRoute
  '/set-username': typeof AuthSetUsernameRoute
  '/verify': typeof AuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/get-started': typeof AuthGetStartedRoute
  '/_auth/set-username': typeof AuthSetUsernameRoute
  '/_auth/verify': typeof AuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/get-started' | '/set-username' | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/get-started' | '/set-username' | '/verify'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/get-started'
    | '/_auth/set-username'
    | '/_auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/get-started': {
      id: '/_auth/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof AuthGetStartedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/set-username': {
      id: '/_auth/set-username'
      path: '/set-username'
      fullPath: '/set-username'
      preLoaderRoute: typeof AuthSetUsernameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthGetStartedRoute: typeof AuthGetStartedRoute
  AuthSetUsernameRoute: typeof AuthSetUsernameRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthGetStartedRoute: AuthGetStartedRoute,
  AuthSetUsernameRoute: AuthSetUsernameRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
