/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/router/__root'
import { Route as AppRouteRouteImport } from './app/router/_app/route'
import { Route as AuthRouteRouteImport } from './app/router/_auth/route'
import { Route as AppIndexRouteImport } from './app/router/_app/index'
import { Route as AppDiscoverRouteImport } from './app/router/_app/discover'
import { Route as AppSearchRouteImport } from './app/router/_app/search'
import { Route as AuthGetStartedRouteImport } from './app/router/_auth/get-started'
import { Route as AuthSetUsernameRouteImport } from './app/router/_auth/set-username'
import { Route as AuthVerifyRouteImport } from './app/router/_auth/verify'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthGetStartedRoute = AuthGetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetUsernameRoute = AuthSetUsernameRouteImport.update({
  id: '/set-username',
  path: '/set-username',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/discover': typeof AppDiscoverRoute
  '/search': typeof AppSearchRoute
  '/get-started': typeof AuthGetStartedRoute
  '/set-username': typeof AuthSetUsernameRoute
  '/verify': typeof AuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/discover': typeof AppDiscoverRoute
  '/search': typeof AppSearchRoute
  '/get-started': typeof AuthGetStartedRoute
  '/set-username': typeof AuthSetUsernameRoute
  '/verify': typeof AuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/search': typeof AppSearchRoute
  '/_auth/get-started': typeof AuthGetStartedRoute
  '/_auth/set-username': typeof AuthSetUsernameRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/discover' | '/search' | '/get-started' | '/set-username' | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/discover' | '/search' | '/get-started' | '/set-username' | '/verify'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/discover'
    | '/_app/search'
    | '/_auth/get-started'
    | '/_auth/set-username'
    | '/_auth/verify'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/get-started': {
      id: '/_auth/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof AuthGetStartedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/set-username': {
      id: '/_auth/set-username'
      path: '/set-username'
      fullPath: '/set-username'
      preLoaderRoute: typeof AuthSetUsernameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthGetStartedRoute: typeof AuthGetStartedRoute
  AuthSetUsernameRoute: typeof AuthSetUsernameRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthGetStartedRoute: AuthGetStartedRoute,
  AuthSetUsernameRoute: AuthSetUsernameRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
